### ISSUE TITLE
Bug report for OKC-PAT

### ISSUE THREAD

**Issue by safadancer** [fabacab/pat-okcupid#3]
I installed the PAT for OKC on Firefox last night and noticed that my OKC immediately became incredibly slow and laggy. I slowly slogged through the 15-question test to activate the PAT, and every time I clicked a radio button, it took several seconds to even register. At about question 3, Firefox froze completely and I had to Force Quit it. When I re-opened, it brought up my previous tabs, including OKC, which remained incredibly slow and laggy as I worked through the rest of the questions. Firefox would not allow me to click through to other tabs, either, as the whole browser was just very confused. When I finished the questions and attempted to browse through OKC suggestions to see if PAT was working, OKC was so slow that I thought Firefox had crashed again and was about to Force Quit when it sloooooowly started to load a photo for a user. I quit Firefox and switched to Chrome to test OKC, and it works fine there. This morning I went back to OKC on Firefox to test if it was still laggy and it definitely is; it took about 5 seconds for each click to register, and I closed the OKC tab before it could crash again.

**Comment by fabacab** [comment]
Thanks so much for looking into this, @focalintent. I've taken your suggestion and committed https://github.com/fabacab/pat-okcupid/commit/9e5b25c37b20c3384e85dff2f4b84d101aa3b1a7 in a new [0.2.4 branch](https://github.com/meitar/pat-okcupid/tree/0.2.4). I think this is better. What do you think?

**Comment by fabacab** [comment]
Yeah, that error is because [GAE currently responds with an error instead of with JSON](https://github.com/fabacab/pat-okcupid/issues/7#issuecomment-17582036), so I'm inclined to believe it's unrelated to this issue.

Thanks for taking a look at this! I'll be releasing version 0.2.4 with this patch shortly.
